name: Publish

on:
    release:
        types: [published]

jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        timeout-minutes: 15
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Install Node
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  registry-url: https://registry.npmjs.org/

            - name: Verify npm auth
              run: npm whoami
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Install dependencies
              run: npm install --legacy-peer-deps
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Build packages
              run: npm run build:esm
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish packages
              run: npx nx release publish --ver=${{ github.ref_name }}
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
